# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


LangList.delete_all
LangList.create(lang:"Punjabi", lang_jp:"パンジャーブ語")
LangList.create(lang:"Javanese", lang_jp:"ジャワ語")
LangList.create(lang:"Korean", lang_jp:"朝鮮語")
LangList.create(lang:"Vietnamese", lang_jp:"ベトナム語")
LangList.create(lang:"Telugu", lang_jp:"テルグ語")
LangList.create(lang:"Marathi", lang_jp:"マラーティー語")
LangList.create(lang:"Tamil", lang_jp:"タミル語")
LangList.create(lang:"Persian", lang_jp:"ペルシア語")
LangList.create(lang:"Urdo", lang_jp:"ウルドゥー語")
LangList.create(lang:"Italian", lang_jp:"イタリア語")
LangList.create(lang:"Turkish", lang_jp:"トルコ語")
LangList.create(lang:"Gujarati", lang_jp:"グジャラート語")
LangList.create(lang:"Polish", lang_jp:"ポーランド語")
LangList.create(lang:"Ukrainian", lang_jp:"ウクライナ語")
LangList.create(lang:"Malayalam", lang_jp:"マラヤーラム語")
LangList.create(lang:"Kannada", lang_jp:"カンナダ語")
LangList.create(lang:"Azerbaijani", lang_jp:"アゼルバイジャン語")
LangList.create(lang:"Odia", lang_jp:"オリヤー語")
LangList.create(lang:"Burmese", lang_jp:"ビルマ語")
LangList.create(lang:"Thai", lang_jp:"タイ語")
LangList.create(lang:"Chinese", lang_jp:"中国語")
LangList.create(lang:"English", lang_jp:"英語")
LangList.create(lang:"Hindi", lang_jp:"ヒンディー語")
LangList.create(lang:"Spanish", lang_jp:"スペイン語")
LangList.create(lang:"Arabic", lang_jp:"アラビア語")
LangList.create(lang:"Bengali", lang_jp:"ベンガル語")
LangList.create(lang:"Portuguese", lang_jp:"ポルトガル語")
LangList.create(lang:"Russian", lang_jp:"ロシア語")
LangList.create(lang:"Japanese", lang_jp:"日本語")
LangList.create(lang:"German", lang_jp:"ドイツ語")
LangList.create(lang:"French", lang_jp:"フランス語")

IndustryList.delete_all
IndustryList.create(industry:"Food", industry_jp:"食品")
IndustryList.create(industry:"Agriculture", industry_jp:"農林")
IndustryList.create(industry:"Marine products", industry_jp:"水産")
IndustryList.create(industry:"Construction housing", industry_jp:"建設・住宅")
IndustryList.create(industry:"Interior", industry_jp:"インテリア")
IndustryList.create(industry:"Fiber", industry_jp:"繊維")
IndustryList.create(industry:"Chemical", industry_jp:"化学")
IndustryList.create(industry:"Pharmaceutical", industry_jp:"薬品")
IndustryList.create(industry:"Cosmetics", industry_jp:"化粧品")
IndustryList.create(industry:"Metal · Mining", industry_jp:"鉄鋼・金属・鉱業")
IndustryList.create(industry:"Machinery · Plant", industry_jp:"機械・プラント")
IndustryList.create(industry:"Electronic · Electrical equipment", industry_jp:"電子・電気機器")
IndustryList.create(industry:"Automobile", industry_jp:"自動車")
IndustryList.create(industry:"Transportation equipment", industry_jp:"輸送用機器")
IndustryList.create(industry:"Precision", industry_jp:"精密")
IndustryList.create(industry:"Medical equipment", industry_jp:"医療機器")
IndustryList.create(industry:"Printing and office equipment related", industry_jp:"印刷・事務機器関連")
IndustryList.create(industry:"Sports", industry_jp:"スポーツ")
IndustryList.create(industry:"Toy", industry_jp:"玩具")
IndustryList.create(industry:"Other manufacturer", industry_jp:"その他メーカー")
IndustryList.create(industry:"Real estate", industry_jp:"不動産")
IndustryList.create(industry:"Railway · Aviation", industry_jp:"鉄道・航空")
IndustryList.create(industry:"Transportation · Logistics", industry_jp:"運輸・物流")
IndustryList.create(industry:"Power · Gas · Energy", industry_jp:"電力・ガス・エネルギー")
IndustryList.create(industry:"Food service", industry_jp:"フードサービス")
IndustryList.create(industry:"Hotel · Travel", industry_jp:"ホテル・旅行")
IndustryList.create(industry:"Medical · Welfare", industry_jp:"医療・福祉")
IndustryList.create(industry:"Amusement · Leisure", industry_jp:"アミューズメント・レジャー")
IndustryList.create(industry:"Other services", industry_jp:"その他サービス")
IndustryList.create(industry:"Consulting · Research", industry_jp:"コンサルティング・調査")
IndustryList.create(industry:"Human resources", industry_jp:"人材サービス")
IndustryList.create(industry:"Education", industry_jp:"教育")
IndustryList.create(industry:"Trading", industry_jp:"商社")
IndustryList.create(industry:"General trading", industry_jp:"総合商社")
IndustryList.create(industry:"Specialized trading", industry_jp:"専門商社")
IndustryList.create(industry:"Software", industry_jp:"ソフトウエア")
IndustryList.create(industry:"Internet service", industry_jp:"インターネットサービス")
IndustryList.create(industry:"Communication", industry_jp:"通信")
IndustryList.create(industry:"Department store · Supermarket", industry_jp:"百貨店・スーパー")
IndustryList.create(industry:"Convenience store", industry_jp:"コンビニ")
IndustryList.create(industry:"Specialty store", industry_jp:"専門店")
IndustryList.create(industry:"Broadcasting", industry_jp:"放送")
IndustryList.create(industry:"Newspaper", industry_jp:"新聞")
IndustryList.create(industry:"Publication", industry_jp:"出版")
IndustryList.create(industry:"Advertisement", industry_jp:"広告")
IndustryList.create(industry:"Finance", industry_jp:"金融")
IndustryList.create(industry:"Banking · Securities", industry_jp:"銀行・証券")
IndustryList.create(industry:"Credit service", industry_jp:"クレジット")
IndustryList.create(industry:"Leasing · Credit", industry_jp:"信販・リース")
IndustryList.create(industry:"Insurance", industry_jp:"生保・損保")
IndustryList.create(industry:"Corporation · Organization", industry_jp:"公社・団体")
IndustryList.create(industry:"Government agency", industry_jp:"官公庁")
IndustryList.create(industry:"Do not decide", industry_jp:"決めていない")

JobCategoryList.delete_all
JobCategoryList.create(job_category:"Sales", job_category_jp:"営業職")
JobCategoryList.create(job_category:"Planning · Marketing · Management", job_category_jp:"企画・マーケティング・経営・管理職")
JobCategoryList.create(job_category:"Specialist job (Consultant · Legal · Accouting · Finance · Real estate)", job_category_jp:"専門職（コンサルタント・士業・金融・不動産）")
JobCategoryList.create(job_category:"Engineer (Machine · Electric · Electronic · Semiconductor · Control)", job_category_jp:"エンジニア職（機械・電気・電子・半導体・制御）")
JobCategoryList.create(job_category:"Medical · Welfare · Nursing", job_category_jp:"医療・福祉・介護専門職")
JobCategoryList.create(job_category:"Technician · Equipment · Transportation · Logistics", job_category_jp:"技能工・設備・交通・運輸専門職")
JobCategoryList.create(job_category:"Office administration", job_category_jp:"事務・管理専門職")
JobCategoryList.create(job_category:"Foodservice and hospitality", job_category_jp:"サービス・販売・外食専門職")
JobCategoryList.create(job_category:"Creative and media", job_category_jp:"クリエイティブ・デザイナー専門職")
JobCategoryList.create(job_category:"IT engineer (System development · System engineering · Infrastructure)", job_category_jp:"ITエンジニア職（システム開発・SE・インフラ）")
JobCategoryList.create(job_category:"Material · Chemistry · Food · Pharmaceutical Technology Profession", job_category_jp:"素材・化学・食品・医薬品技術職")
JobCategoryList.create(job_category:"Architectural · Civil Engineering Occupation", job_category_jp:"建築・土木技術職")
JobCategoryList.create(job_category:"Do not decide", job_category_jp:"決めていない")


CountryList.delete_all
CountryList.create(country:"Afghanistan", country_jp:"アフガニスタン")
CountryList.create(country:"Albania", country_jp:"アルバニア")
CountryList.create(country:"Algeria", country_jp:"アルジェリア")
CountryList.create(country:"Andorra", country_jp:"アンドラ")
CountryList.create(country:"Angola", country_jp:"アンゴラ")
CountryList.create(country:"Antigua and Barbuda", country_jp:"アンチグア・バーブーダ")
CountryList.create(country:"Argentina", country_jp:"アルゼンチン")
CountryList.create(country:"Armenia", country_jp:"アルメニア")
CountryList.create(country:"Australia", country_jp:"オーストラリア")
CountryList.create(country:"Austria", country_jp:"オーストリア")
CountryList.create(country:"Azerbaijan", country_jp:"アゼルバイジャン")
CountryList.create(country:"Bahamas", country_jp:"バハマ")
CountryList.create(country:"Bahrain", country_jp:"バーレーン")
CountryList.create(country:"Bangladesh", country_jp:"バングラデシュ")
CountryList.create(country:"Barbados", country_jp:"バルバドス")
CountryList.create(country:"Belarus", country_jp:"ベラルーシ")
CountryList.create(country:"Belgium", country_jp:"ベルギー")
CountryList.create(country:"Belize", country_jp:"ベリーズ")
CountryList.create(country:"Benin", country_jp:"ベナン")
CountryList.create(country:"Bhutan", country_jp:"ブータン")
CountryList.create(country:"Bolivia", country_jp:"ボリビア")
CountryList.create(country:"Bosnia and Herzegovina", country_jp:"ボスニア・ヘルツェゴビナ")
CountryList.create(country:"Botswana", country_jp:"ボツワナ")
CountryList.create(country:"Brazil", country_jp:"ブラジル")
CountryList.create(country:"Brunei Darussalam", country_jp:"ブルネイ")
CountryList.create(country:"Bulgaria", country_jp:"ブルガリア")
CountryList.create(country:"Burkina Faso", country_jp:"ブルキナファソ")
CountryList.create(country:"Burundi", country_jp:"ブルンジ")
CountryList.create(country:"Cabo Verde", country_jp:"カーボベルデ")
CountryList.create(country:"Cambodia", country_jp:"カンボジア")
CountryList.create(country:"Cameroon", country_jp:"カメルーン")
CountryList.create(country:"Canada", country_jp:"カナダ")
CountryList.create(country:"Central African Republic", country_jp:"中央アフリカ共和国")
CountryList.create(country:"Chad", country_jp:"チャド")
CountryList.create(country:"Chile", country_jp:"チリ")
CountryList.create(country:"China", country_jp:"中国")
CountryList.create(country:"Colombia", country_jp:"コロンビア")
CountryList.create(country:"Comoros", country_jp:"コモロ")
CountryList.create(country:"Congo", country_jp:"コンゴ")
CountryList.create(country:"Costa Rica", country_jp:"コスタリカ")
CountryList.create(country:"Cote D'Ivoire", country_jp:"コートジボアール")
CountryList.create(country:"Croatia", country_jp:"クロアチア")
CountryList.create(country:"Cuba", country_jp:"キューバ")
CountryList.create(country:"Cyprus", country_jp:"キプロス")
CountryList.create(country:"Czech Republic", country_jp:"チェコ")
CountryList.create(country:"Democratic People's Republic of Korea", country_jp:"朝鮮民主主義人民共和国")
CountryList.create(country:"Democratic Republic of the Congo", country_jp:"コンゴ民主共和国")
CountryList.create(country:"Denmark", country_jp:"デンマーク")
CountryList.create(country:"Djibouti", country_jp:"ジブチ")
CountryList.create(country:"Dominica", country_jp:"ドミニカ")
CountryList.create(country:"Dominican Republic", country_jp:"ドミニカ共和国")
CountryList.create(country:"Ecuador", country_jp:"エクアドル")
CountryList.create(country:"Egypt", country_jp:"エジプト")
CountryList.create(country:"El Salvador", country_jp:"エルサルバドル")
CountryList.create(country:"Equatorial Guinea", country_jp:"赤道ギニア")
CountryList.create(country:"Eritrea", country_jp:"エリトリア")
CountryList.create(country:"Estonia", country_jp:"エストニア")
CountryList.create(country:"Ethiopia", country_jp:"エチオピア")
CountryList.create(country:"Fiji", country_jp:"フィジ－")
CountryList.create(country:"Finland", country_jp:"フィンランド")
CountryList.create(country:"France", country_jp:"フランス")
CountryList.create(country:"Gabon", country_jp:"ガボン")
CountryList.create(country:"Gambia", country_jp:"ガンビア")
CountryList.create(country:"Georgia", country_jp:"ジョージア")
CountryList.create(country:"Germany", country_jp:"ドイツ")
CountryList.create(country:"Ghana", country_jp:"ガーナ")
CountryList.create(country:"Greece", country_jp:"ギリシャ")
CountryList.create(country:"Grenada", country_jp:"グレナダ")
CountryList.create(country:"Guatemala", country_jp:"グアテマラ")
CountryList.create(country:"Guinea", country_jp:"ギニア")
CountryList.create(country:"Guinea Bissau", country_jp:"ギニアビサウ")
CountryList.create(country:"Guyana", country_jp:"ガイアナ")
CountryList.create(country:"Haiti", country_jp:"ハイチ")
CountryList.create(country:"Honduras", country_jp:"ホンジュラス")
CountryList.create(country:"Hungary", country_jp:"ハンガリ－")
CountryList.create(country:"Iceland", country_jp:"アイスランド")
CountryList.create(country:"India", country_jp:"インド")
CountryList.create(country:"Indonesia", country_jp:"インドネシア")
CountryList.create(country:"Iran", country_jp:"イラン")
CountryList.create(country:"Iraq", country_jp:"イラク")
CountryList.create(country:"Ireland", country_jp:"アイルランド")
CountryList.create(country:"Israel", country_jp:"イスラエル")
CountryList.create(country:"Italy", country_jp:"イタリア")
CountryList.create(country:"Jamaica", country_jp:"ジャマイカ")
CountryList.create(country:"Japan", country_jp:"日本")
CountryList.create(country:"Jordan", country_jp:"ヨルダン")
CountryList.create(country:"Kazakhstan", country_jp:"カザフスタン")
CountryList.create(country:"Kenya", country_jp:"ケニア")
CountryList.create(country:"Kiribati", country_jp:"キリバス")
CountryList.create(country:"Kuwait", country_jp:"クウェート")
CountryList.create(country:"Kyrgyzstan", country_jp:"キルギスタン")
CountryList.create(country:"Laos", country_jp:"ラオス人民民主共和国")
CountryList.create(country:"Latvia", country_jp:"ラトビア")
CountryList.create(country:"Lebanon", country_jp:"レバノン")
CountryList.create(country:"Lesotho", country_jp:"レソト")
CountryList.create(country:"Liberia", country_jp:"リベリア")
CountryList.create(country:"Libya", country_jp:"リビア")
CountryList.create(country:"Liechtenstein", country_jp:"リヒテンシュタイン")
CountryList.create(country:"Lithuania", country_jp:"リトアニア")
CountryList.create(country:"Luxembourg", country_jp:"ルクセンブルク")
CountryList.create(country:"Madagascar", country_jp:"マダガスカル")
CountryList.create(country:"Malawi", country_jp:"マラウィ")
CountryList.create(country:"Malaysia", country_jp:"マレーシア")
CountryList.create(country:"Maldives", country_jp:"モルディブ")
CountryList.create(country:"Mali", country_jp:"マリ")
CountryList.create(country:"Malta", country_jp:"マルタ")
CountryList.create(country:"Marshall Islands", country_jp:"マーシャル諸島")
CountryList.create(country:"Mauritania", country_jp:"モーリタニア")
CountryList.create(country:"Mauritius", country_jp:"モーリシャス")
CountryList.create(country:"Mexico", country_jp:"メキシコ")
CountryList.create(country:"Micronesia", country_jp:"ミクロネシア連邦")
CountryList.create(country:"Monaco", country_jp:"モナコ")
CountryList.create(country:"Mongolia", country_jp:"モンゴル")
CountryList.create(country:"Montenegro", country_jp:"モンテネグロ")
CountryList.create(country:"Morocco", country_jp:"モロッコ")
CountryList.create(country:"Mozambique", country_jp:"モザンビーク")
CountryList.create(country:"Myanmar", country_jp:"ミャンマー")
CountryList.create(country:"Namibia", country_jp:"ナミビア")
CountryList.create(country:"Nauru", country_jp:"ナウル")
CountryList.create(country:"Nepal", country_jp:"ネパール")
CountryList.create(country:"Netherlands", country_jp:"オランダ")
CountryList.create(country:"New Zealand", country_jp:"ニュージーランド")
CountryList.create(country:"Nicaragua", country_jp:"ニカラグア")
CountryList.create(country:"Niger", country_jp:"ニジェール")
CountryList.create(country:"Nigeria", country_jp:"ナイジェリア")
CountryList.create(country:"Norway", country_jp:"ノルウェー")
CountryList.create(country:"Oman", country_jp:"オマーン")
CountryList.create(country:"Pakistan", country_jp:"パキスタン")
CountryList.create(country:"Palau", country_jp:"パラオ")
CountryList.create(country:"Panama", country_jp:"パナマ")
CountryList.create(country:"Papua New Guinea", country_jp:"パプア・ニューギニア")
CountryList.create(country:"Paraguay", country_jp:"パラグアイ")
CountryList.create(country:"Peru", country_jp:"ペル－")
CountryList.create(country:"Philippines", country_jp:"フィリピン")
CountryList.create(country:"Poland", country_jp:"ポーランド")
CountryList.create(country:"Portugal", country_jp:"ポルトガル")
CountryList.create(country:"Qatar", country_jp:"カタール")
CountryList.create(country:"Korea", country_jp:"韓国")
CountryList.create(country:"Moldova", country_jp:"モルドバ")
CountryList.create(country:"Romania", country_jp:"ルーマニア")
CountryList.create(country:"Russia", country_jp:"ロシア連邦")
CountryList.create(country:"Rwanda", country_jp:"ルワンダ")
CountryList.create(country:"Saint Kitts and Nevis", country_jp:"セントクリストファー・ネイビス")
CountryList.create(country:"Saint Lucia", country_jp:"セントルシア")
CountryList.create(country:"Saint Vincent and the Grenadines", country_jp:"セントビンセントおよびグレナディーン諸島")
CountryList.create(country:"Samoa", country_jp:"サモア")
CountryList.create(country:"San Marino", country_jp:"サンマリノ")
CountryList.create(country:"Sao Tome and Principe", country_jp:"サントメ・プリンシペ")
CountryList.create(country:"Saudi Arabia", country_jp:"サウジアラビア")
CountryList.create(country:"Senegal", country_jp:"セネガル")
CountryList.create(country:"Serbia", country_jp:"セルビア")
CountryList.create(country:"Seychelles", country_jp:"セイシェル")
CountryList.create(country:"Sierra Leone", country_jp:"シエラレオネ")
CountryList.create(country:"Singapore", country_jp:"シンガポール")
CountryList.create(country:"Slovakia", country_jp:"スロバキア")
CountryList.create(country:"Slovenia", country_jp:"スロベニア")
CountryList.create(country:"Solomon Islands", country_jp:"ソロモン諸島")
CountryList.create(country:"Somalia", country_jp:"ソマリア")
CountryList.create(country:"South Africa", country_jp:"南アフリカ")
CountryList.create(country:"South Sudan", country_jp:"南スーダン")
CountryList.create(country:"Spain", country_jp:"スペイン")
CountryList.create(country:"Sri Lanka", country_jp:"スリランカ")
CountryList.create(country:"Sudan", country_jp:"スーダン")
CountryList.create(country:"Suriname", country_jp:"スリナム")
CountryList.create(country:"Swaziland", country_jp:"スワジランド")
CountryList.create(country:"Sweden", country_jp:"スウェーデン")
CountryList.create(country:"Switzerland", country_jp:"スイス")
CountryList.create(country:"Syria", country_jp:"シリア")
CountryList.create(country:"Tajikistan", country_jp:"タジキスタン")
CountryList.create(country:"Thailand", country_jp:"タイ")
CountryList.create(country:"Macedonia", country_jp:"マケドニア・旧ユーゴスラビア共和国")
CountryList.create(country:"Timor-Leste", country_jp:"東ティモール")
CountryList.create(country:"Togo", country_jp:"トーゴ")
CountryList.create(country:"Tonga", country_jp:"トンガ")
CountryList.create(country:"Trinidad and Tobago", country_jp:"トリニダード・トバゴ")
CountryList.create(country:"Tunisia", country_jp:"チュニジア")
CountryList.create(country:"Turkey", country_jp:"トルコ")
CountryList.create(country:"Turkmenistan", country_jp:"トルクメニスタン")
CountryList.create(country:"Tuvalu", country_jp:"ツバル")
CountryList.create(country:"Uganda", country_jp:"ウガンダ")
CountryList.create(country:"Ukraine", country_jp:"ウクライナ")
CountryList.create(country:"United Arab Emirates", country_jp:"アラブ首長国連邦")
CountryList.create(country:"United Kingdom", country_jp:"イギリス")
CountryList.create(country:"United Republic of Tanzania", country_jp:"タンザニア")
CountryList.create(country:"United States of America", country_jp:"アメリカ")
CountryList.create(country:"Uruguay", country_jp:"ウルグアイ")
CountryList.create(country:"Uzbekistan", country_jp:"ウズベキスタン")
CountryList.create(country:"Vanuatu", country_jp:"バヌアツ")
CountryList.create(country:"Venezuela", country_jp:"ベネズエラ")
CountryList.create(country:"Viet Nam", country_jp:"ベトナム")
CountryList.create(country:"Yemen", country_jp:"イエメン")
CountryList.create(country:"Zambia", country_jp:"ザンビア")
CountryList.create(country:"Zimbabwe", country_jp:"ジンバブエ")
