# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


LangList.delete_all
LangList.create(lang:"Punjabi", lang_jp:"パンジャーブ語")
LangList.create(lang:"Javanese", lang_jp:"ジャワ語")
LangList.create(lang:"Korean", lang_jp:"朝鮮語")
LangList.create(lang:"Vietnamese", lang_jp:"ベトナム語")
LangList.create(lang:"Telugu", lang_jp:"テルグ語")
LangList.create(lang:"Marathi", lang_jp:"マラーティー語")
LangList.create(lang:"Tamil", lang_jp:"タミル語")
LangList.create(lang:"Persian", lang_jp:"ペルシア語")
LangList.create(lang:"Urdo", lang_jp:"ウルドゥー語")
LangList.create(lang:"Italian", lang_jp:"イタリア語")
LangList.create(lang:"Turkish", lang_jp:"トルコ語")
LangList.create(lang:"Gujarati", lang_jp:"グジャラート語")
LangList.create(lang:"Polish", lang_jp:"ポーランド語")
LangList.create(lang:"Ukrainian", lang_jp:"ウクライナ語")
LangList.create(lang:"Malayalam", lang_jp:"マラヤーラム語")
LangList.create(lang:"Kannada", lang_jp:"カンナダ語")
LangList.create(lang:"Azerbaijani", lang_jp:"アゼルバイジャン語")
LangList.create(lang:"Odia", lang_jp:"オリヤー語")
LangList.create(lang:"Burmese", lang_jp:"ビルマ語")
LangList.create(lang:"Thai", lang_jp:"タイ語")
LangList.create(lang:"Chinese", lang_jp:"中国語")
LangList.create(lang:"English", lang_jp:"英語")
LangList.create(lang:"Hindi", lang_jp:"ヒンディー語")
LangList.create(lang:"Spanish", lang_jp:"スペイン語")
LangList.create(lang:"Arabic", lang_jp:"アラビア語")
LangList.create(lang:"Bengali", lang_jp:"ベンガル語")
LangList.create(lang:"Portuguese", lang_jp:"ポルトガル語")
LangList.create(lang:"Russian", lang_jp:"ロシア語")
LangList.create(lang:"Japanese", lang_jp:"日本語")
LangList.create(lang:"German", lang_jp:"ドイツ語")
LangList.create(lang:"French", lang_jp:"フランス語")

IndustryList.delete_all
IndustryList.create(industry:"Food", industry_jp:"食品")
IndustryList.create(industry:"Agriculture", industry_jp:"農林")
IndustryList.create(industry:"Marine products", industry_jp:"水産")
IndustryList.create(industry:"Construction housing", industry_jp:"建設・住宅")
IndustryList.create(industry:"Interior", industry_jp:"インテリア")
IndustryList.create(industry:"Fiber", industry_jp:"繊維")
IndustryList.create(industry:"Chemical", industry_jp:"化学")
IndustryList.create(industry:"Pharmaceutical", industry_jp:"薬品")
IndustryList.create(industry:"Cosmetics", industry_jp:"化粧品")
IndustryList.create(industry:"Metal · Mining", industry_jp:"鉄鋼・金属・鉱業")
IndustryList.create(industry:"Machinery · Plant", industry_jp:"機械・プラント")
IndustryList.create(industry:"Electronic · Electrical equipment", industry_jp:"電子・電気機器")
IndustryList.create(industry:"Automobile", industry_jp:"自動車")
IndustryList.create(industry:"Transportation equipment", industry_jp:"輸送用機器")
IndustryList.create(industry:"Precision", industry_jp:"精密")
IndustryList.create(industry:"Medical equipment", industry_jp:"医療機器")
IndustryList.create(industry:"Printing and office equipment related", industry_jp:"印刷・事務機器関連")
IndustryList.create(industry:"Sports", industry_jp:"スポーツ")
IndustryList.create(industry:"Toy", industry_jp:"玩具")
IndustryList.create(industry:"Other manufacturer", industry_jp:"その他メーカー")
IndustryList.create(industry:"Real estate", industry_jp:"不動産")
IndustryList.create(industry:"Railway · Aviation", industry_jp:"鉄道・航空")
IndustryList.create(industry:"Transportation · Logistics", industry_jp:"運輸・物流")
IndustryList.create(industry:"Power · Gas · Energy", industry_jp:"電力・ガス・エネルギー")
IndustryList.create(industry:"Food service", industry_jp:"フードサービス")
IndustryList.create(industry:"Hotel · Travel", industry_jp:"ホテル・旅行")
IndustryList.create(industry:"Medical · Welfare", industry_jp:"医療・福祉")
IndustryList.create(industry:"Amusement · Leisure", industry_jp:"アミューズメント・レジャー")
IndustryList.create(industry:"Other services", industry_jp:"その他サービス")
IndustryList.create(industry:"Consulting · Research", industry_jp:"コンサルティング・調査")
IndustryList.create(industry:"Human resources", industry_jp:"人材サービス")
IndustryList.create(industry:"Education", industry_jp:"教育")
IndustryList.create(industry:"Trading", industry_jp:"商社")
IndustryList.create(industry:"General trading", industry_jp:"総合商社")
IndustryList.create(industry:"Specialized trading", industry_jp:"専門商社")
IndustryList.create(industry:"Software", industry_jp:"ソフトウエア")
IndustryList.create(industry:"Internet service", industry_jp:"インターネットサービス")
IndustryList.create(industry:"Communication", industry_jp:"通信")
IndustryList.create(industry:"Department store · Supermarket", industry_jp:"百貨店・スーパー")
IndustryList.create(industry:"Convenience store", industry_jp:"コンビニ")
IndustryList.create(industry:"Specialty store", industry_jp:"専門店")
IndustryList.create(industry:"Broadcasting", industry_jp:"放送")
IndustryList.create(industry:"Newspaper", industry_jp:"新聞")
IndustryList.create(industry:"Publication", industry_jp:"出版")
IndustryList.create(industry:"Advertisement", industry_jp:"広告")
IndustryList.create(industry:"Finance", industry_jp:"金融")
IndustryList.create(industry:"Banking · Securities", industry_jp:"銀行・証券")
IndustryList.create(industry:"Credit service", industry_jp:"クレジット")
IndustryList.create(industry:"Leasing · Credit", industry_jp:"信販・リース")
IndustryList.create(industry:"Insurance", industry_jp:"生保・損保")
IndustryList.create(industry:"Corporation · Organization", industry_jp:"公社・団体")
IndustryList.create(industry:"Government agency", industry_jp:"官公庁")
IndustryList.create(industry:"Do not decide", industry_jp:"決めていない")

JobCategoryList.delete_all
JobCategoryList.create(job_category:"Sales", job_category_jp:"営業職")
JobCategoryList.create(job_category:"Planning · Marketing · Management", job_category_jp:"企画・マーケティング・経営・管理職")
JobCategoryList.create(job_category:"Specialist job (Consultant · Legal · Accouting · Finance · Real estate)", job_category_jp:"専門職（コンサルタント・士業・金融・不動産）")
JobCategoryList.create(job_category:"Engineer (Machine · Electric · Electronic · Semiconductor · Control)", job_category_jp:"エンジニア職（機械・電気・電子・半導体・制御）")
JobCategoryList.create(job_category:"Medical · Welfare · Nursing", job_category_jp:"医療・福祉・介護専門職")
JobCategoryList.create(job_category:"Technician · Equipment · Transportation · Logistics", job_category_jp:"技能工・設備・交通・運輸専門職")
JobCategoryList.create(job_category:"Office administration", job_category_jp:"事務・管理専門職")
JobCategoryList.create(job_category:"Foodservice and hospitality", job_category_jp:"サービス・販売・外食専門職")
JobCategoryList.create(job_category:"Creative and media", job_category_jp:"クリエイティブ・デザイナー専門職")
JobCategoryList.create(job_category:"IT engineer (System development · System engineering · Infrastructure)", job_category_jp:"ITエンジニア職（システム開発・SE・インフラ）")
JobCategoryList.create(job_category:"Material · Chemistry · Food · Pharmaceutical Technology Profession", job_category_jp:"素材・化学・食品・医薬品技術職")
JobCategoryList.create(job_category:"Architectural · Civil Engineering Occupation", job_category_jp:"建築・土木技術職")
JobCategoryList.create(job_category:"Do not decide", job_category_jp:"決めていない")


